- name: Download flannel manifest
  get_url:
    url: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
    dest: /tmp/kube-flannel.yml
    mode: '0755'

# - name: Modify Flannel ConfigMap podCIDR
#   lineinfile:
#     path: "/tmp/kube-flannel.yml"
#     regexp: '"Network": ".*"'  # Regex to match the podCIDR line
#     line: '      "Network": "172.20.0.0/16",'  # Replace with your desired CIDR
#     backrefs: yes
- name: Create cni directory
  file:
    path: /opt/cni/bin
    state: directory

- name: Download and setup cni plugins
  unarchive:
    src: "{{ cni_plugins_url }}/{{ cni_plugins_version }}/{{ cni_plugins_tarball }}"
    dest: "/opt/cni/bin"
    remote_src: yes
    extra_opts:
      - --strip-components=1
  retries: 3
  delay: 5

- name: Set up Flannel CNI from manifest
  command: kubectl create -f /tmp/kube-flannel.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
