- name: Install Runtime and Kubernetes
  hosts:
    - masters
    - workers
  roles:
    - runtime
    - download-k8s
    - install-k8s

- name: Install networking - flannel
  hosts: masters
  roles:
    - install-flannel
