- name: Create cni directory
  file:
    path: /opt/cni/bin
    state: directory

- name: Download and setup cni plugins
  unarchive:
    src: "{{ cni_plugins_url }}/{{ cni_plugins_version }}/{{ cni_plugins_tarball }}"
    dest: "/opt/cni/bin"
    remote_src: yes
    extra_opts:
      - --strip-components=1
  retries: 3
  delay: 5
